name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: install
        run: npm install
        working-directory: web

      - name: build
        run: npm run codegen;npm run build
        working-directory: web

      - name: inject-analytics
        run: misc/apply.sh dist/index.html
        working-directory: web

      - name: deploy (repo)
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          commit-message: "@${{ github.sha }}"
          branch: gh-pages
          folder: web/dist

